name: Create Distro

on:
  release:
    types: [created]

jobs:
  Linux-Distro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: NPM install
        shell: bash
        run: |
          cd /home/runner/work/nednetwork/nednetwork
          npm install

      - name: Create ZIP distro for Linux
        shell: bash
        run: |
          cp $(which node) /home/runner/work/nednetwork/nednetwork/.
          cd /home/runner/work/nednetwork/
          zip -r nednetwork-linux-x64.zip nednetwork/*

      - name: Upload Linux distro
        uses: actions/upload-artifact@v1
        with:
          name: nednetwork-linux-x64.zip
          path: /home/runner/work/nednetwork/nednetwork-linux-x64.zip
          
  Get-Windows-Node-Files:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM install
        shell: cmd
        run: npm install "d:\a\nednetwork\nednetwork"
          
      - name: Upload Windows Node exe
        uses: actions/upload-artifact@v1
        with:
          name: win-node-exe
          path: "c:\\Program Files\\nodejs\\node.exe"

      - name: Upload Node Modules for Windows
        uses: actions/upload-artifact@v1
        with: 
          name: win-node-modules
          path: node_modules

  Build-Windows-Distro:
    needs: Get-Windows-Node-Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Windows Node exe
        uses: actions/download-artifact@v1
        with: 
          name: win-node-exe
      
      - name: Get Windows Node modules
        uses: actions/download-artifact@v1
        with: 
          name: win-node-modules

      - name: Extract files
        shell: bash
        run: |
          WORK_DIR=/home/runner/work/nednetwork/nednetwork
          mkdir $WORK_DIR/node_modules
          mv $WORK_DIR/win-node-modules/* $WORK_DIR/node_modules/
          mv $WORK_DIR/win-node-exe/* $WORK_DIR/.
          [ -d $WORK_DIR/win-node-exe ] && rm -r $WORK_DIR/win-node-exe
          [ -d $WORK_DIR/win-node-modules ] && rm -r $WORK_DIR/win-node-modules

      - name: Create ZIP distro for Windows
        shell: bash
        run: |
          cd /home/runner/work/nednetwork/
          zip -r nednetwork-windows-x64.zip nednetwork/*

      - name: Upload Windows distro
        uses: actions/upload-artifact@v1
        with: 
          name: nednetwork-windows-x64.zip
          path: /home/runner/work/nednetwork/nednetwork-windows-x64.zip

  Publish-Binaries:
    needs: [Build-Windows-Distro, Linux-Distro]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows distro
        uses: actions/download-artifact@v1
        with: 
          name: nednetwork-windows-x64.zip

      - name: Download Linux distro
        uses: actions/download-artifact@v1
        with:
          name: nednetwork-linux-x64.zip

      - name: Publish binaries
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'nednetwork-windows-x64.zip nednetwork-linux-x64.zip'
